# Generated by Django 2.1.7 on 2019-04-22 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_code',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postcode',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='puzzle/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='specie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Specie'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='specie_desc',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_score',
            field=models.IntegerField(default=100),
        ),
    ]
