# Generated by Django 2.1.7 on 2019-04-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0003_auto_20190422_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=20, null=True)),
                ('food_img', models.ImageField(blank=True, null=True, upload_to='puzzle/')),
                ('food_score', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolName', models.CharField(max_length=20, null=True)),
                ('tool_img', models.ImageField(blank=True, null=True, upload_to='puzzle/')),
                ('tool_score', models.IntegerField(default=20)),
            ],
        ),
    ]
