# Generated by Django 2.1.7 on 2019-04-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_food_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_code',
        ),
        migrations.AddField(
            model_name='specie',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Food'),
        ),
    ]
