# Generated by Django 2.1.7 on 2019-05-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0008_auto_20190429_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='map',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
