# Generated by Django 2.1.7 on 2019-05-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0009_specie_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='zoo_address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
