# Generated by Django 2.1.7 on 2019-04-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='specie',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='puzzle/'),
        ),
        migrations.AlterField(
            model_name='specie',
            name='specie_desc',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
