# Generated by Django 2.1.7 on 2019-04-08 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_auto_20190408_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='specie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Specie'),
        ),
    ]
