# Generated by Django 2.1.7 on 2019-04-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0003_photo_specie'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_code',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
