# Generated by Django 2.1.7 on 2019-04-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0006_auto_20190425_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='food',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='photo',
        ),
        migrations.AddField(
            model_name='food',
            name='specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Specie'),
        ),
        migrations.AddField(
            model_name='photo',
            name='specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Specie'),
        ),
    ]
