# Generated by Django 2.1.7 on 2019-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0007_auto_20190425_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='specie',
            name='diff',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='easy',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='specie',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to='puzzle/'),
        ),
    ]
